services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped

  mosquitto-test:
    image: eclipse-mosquitto:2.0
    depends_on:
      - mosquitto
    volumes:
      - ./test:/test
    entrypoint: ["/bin/sh", "/test/test-e2e.sh"]
